# Generated by Django 4.2.3 on 2023-07-07 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.day')),
                ('Syllabus', models.ManyToManyField(blank=True, null=True, to='myapp.syllabus')),
            ],
        ),
    ]
